% Test script to verify that the matlab code is working ahead of
% compilation.
%
% SPM12 needs to be in the matlab path.
%
% We also need some test data in the ../INPUTS directory, and the
% ../OUTPUTS directory must exist.

magm_normalize( ...
	't1_niigz','../INPUTS/t1.nii.gz', ...
	'seg_niigz','../INPUTS/seg.nii.gz', ...
	'out_dir','../OUTPUTS', ...
	'xnat_proj','TEST_PROJ', ...
	'xnat_subj','TEST_SUBJ', ...
	'xnat_sess','TEST_SESS', ...
	'xnat_t1scan','TEST_SCAN' ...
	);
