addpath(genpath('${code_path}'));
magm_coreg_normalize_v2( ...
	'${t1_file}', ...
	'${seg_file}', ...
	'${temp_dir}', ...
	'${spm12_path}', ...
	'${project}', ...
	'${subject}', ...
	'${session}', ...
	'${scan}' ...
);
